// 전국 252개 시군구 행정구역 코드 표 (행안부 5자리 법정동 기준)
export interface RegionItem {
  code: string;
  name: string;
  sidoCode: string;
  sidoName: string;
  fullName: string;
}

export const REGIONS: RegionItem[] = [
  {
    code: "11010",
    name: "종로구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 종로구",
  },
  {
    code: "11020",
    name: "중구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 중구",
  },
  {
    code: "11030",
    name: "용산구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 용산구",
  },
  {
    code: "11040",
    name: "성동구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 성동구",
  },
  {
    code: "11050",
    name: "광진구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 광진구",
  },
  {
    code: "11060",
    name: "동대문구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 동대문구",
  },
  {
    code: "11070",
    name: "중랑구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 중랑구",
  },
  {
    code: "11080",
    name: "성북구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 성북구",
  },
  {
    code: "11090",
    name: "강북구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 강북구",
  },
  {
    code: "11100",
    name: "도봉구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 도봉구",
  },
  {
    code: "11110",
    name: "노원구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 노원구",
  },
  {
    code: "11120",
    name: "은평구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 은평구",
  },
  {
    code: "11130",
    name: "서대문구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 서대문구",
  },
  {
    code: "11140",
    name: "마포구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 마포구",
  },
  {
    code: "11150",
    name: "양천구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 양천구",
  },
  {
    code: "11160",
    name: "강서구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 강서구",
  },
  {
    code: "11170",
    name: "구로구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 구로구",
  },
  {
    code: "11180",
    name: "금천구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 금천구",
  },
  {
    code: "11190",
    name: "영등포구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 영등포구",
  },
  {
    code: "11200",
    name: "동작구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 동작구",
  },
  {
    code: "11210",
    name: "관악구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 관악구",
  },
  {
    code: "11220",
    name: "서초구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 서초구",
  },
  {
    code: "11230",
    name: "강남구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 강남구",
  },
  {
    code: "11240",
    name: "송파구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 송파구",
  },
  {
    code: "11250",
    name: "강동구",
    sidoCode: "11",
    sidoName: "서울특별시",
    fullName: "서울특별시 강동구",
  },
  {
    code: "21010",
    name: "중구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 중구",
  },
  {
    code: "21020",
    name: "서구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 서구",
  },
  {
    code: "21030",
    name: "동구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 동구",
  },
  {
    code: "21040",
    name: "영도구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 영도구",
  },
  {
    code: "21050",
    name: "부산진구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 부산진구",
  },
  {
    code: "21060",
    name: "동래구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 동래구",
  },
  {
    code: "21070",
    name: "남구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 남구",
  },
  {
    code: "21080",
    name: "북구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 북구",
  },
  {
    code: "21090",
    name: "해운대구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 해운대구",
  },
  {
    code: "21100",
    name: "사하구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 사하구",
  },
  {
    code: "21110",
    name: "금정구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 금정구",
  },
  {
    code: "21120",
    name: "강서구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 강서구",
  },
  {
    code: "21130",
    name: "연제구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 연제구",
  },
  {
    code: "21140",
    name: "수영구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 수영구",
  },
  {
    code: "21150",
    name: "사상구",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 사상구",
  },
  {
    code: "21510",
    name: "기장군",
    sidoCode: "21",
    sidoName: "기타",
    fullName: "기타 기장군",
  },
  {
    code: "22010",
    name: "중구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 중구",
  },
  {
    code: "22020",
    name: "동구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 동구",
  },
  {
    code: "22030",
    name: "서구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 서구",
  },
  {
    code: "22040",
    name: "남구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 남구",
  },
  {
    code: "22050",
    name: "북구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 북구",
  },
  {
    code: "22060",
    name: "수성구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 수성구",
  },
  {
    code: "22070",
    name: "달서구",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 달서구",
  },
  {
    code: "22510",
    name: "달성군",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 달성군",
  },
  {
    code: "22520",
    name: "군위군",
    sidoCode: "22",
    sidoName: "기타",
    fullName: "기타 군위군",
  },
  {
    code: "23010",
    name: "중구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 중구",
  },
  {
    code: "23020",
    name: "동구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 동구",
  },
  {
    code: "23040",
    name: "연수구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 연수구",
  },
  {
    code: "23050",
    name: "남동구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 남동구",
  },
  {
    code: "23060",
    name: "부평구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 부평구",
  },
  {
    code: "23070",
    name: "계양구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 계양구",
  },
  {
    code: "23080",
    name: "서구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 서구",
  },
  {
    code: "23090",
    name: "남구",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 남구",
  },
  {
    code: "23510",
    name: "강화군",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 강화군",
  },
  {
    code: "23520",
    name: "옹진군",
    sidoCode: "23",
    sidoName: "기타",
    fullName: "기타 옹진군",
  },
  {
    code: "24010",
    name: "동구",
    sidoCode: "24",
    sidoName: "기타",
    fullName: "기타 동구",
  },
  {
    code: "24020",
    name: "서구",
    sidoCode: "24",
    sidoName: "기타",
    fullName: "기타 서구",
  },
  {
    code: "24030",
    name: "남구",
    sidoCode: "24",
    sidoName: "기타",
    fullName: "기타 남구",
  },
  {
    code: "24040",
    name: "북구",
    sidoCode: "24",
    sidoName: "기타",
    fullName: "기타 북구",
  },
  {
    code: "24050",
    name: "광산구",
    sidoCode: "24",
    sidoName: "기타",
    fullName: "기타 광산구",
  },
  {
    code: "25010",
    name: "동구",
    sidoCode: "25",
    sidoName: "기타",
    fullName: "기타 동구",
  },
  {
    code: "25020",
    name: "중구",
    sidoCode: "25",
    sidoName: "기타",
    fullName: "기타 중구",
  },
  {
    code: "25030",
    name: "서구",
    sidoCode: "25",
    sidoName: "기타",
    fullName: "기타 서구",
  },
  {
    code: "25040",
    name: "유성구",
    sidoCode: "25",
    sidoName: "기타",
    fullName: "기타 유성구",
  },
  {
    code: "25050",
    name: "대덕구",
    sidoCode: "25",
    sidoName: "기타",
    fullName: "기타 대덕구",
  },
  {
    code: "26010",
    name: "중구",
    sidoCode: "26",
    sidoName: "부산광역시",
    fullName: "부산광역시 중구",
  },
  {
    code: "26020",
    name: "남구",
    sidoCode: "26",
    sidoName: "부산광역시",
    fullName: "부산광역시 남구",
  },
  {
    code: "26030",
    name: "동구",
    sidoCode: "26",
    sidoName: "부산광역시",
    fullName: "부산광역시 동구",
  },
  {
    code: "26040",
    name: "북구",
    sidoCode: "26",
    sidoName: "부산광역시",
    fullName: "부산광역시 북구",
  },
  {
    code: "26510",
    name: "울주군",
    sidoCode: "26",
    sidoName: "부산광역시",
    fullName: "부산광역시 울주군",
  },
  {
    code: "29010",
    name: "세종특별자치시",
    sidoCode: "29",
    sidoName: "광주광역시",
    fullName: "광주광역시 세종특별자치시",
  },
  {
    code: "31011",
    name: "수원시 장안구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 수원시 장안구",
  },
  {
    code: "31012",
    name: "수원시 권선구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 수원시 권선구",
  },
  {
    code: "31013",
    name: "수원시 팔달구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 수원시 팔달구",
  },
  {
    code: "31014",
    name: "수원시 영통구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 수원시 영통구",
  },
  {
    code: "31021",
    name: "성남시 수정구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 성남시 수정구",
  },
  {
    code: "31022",
    name: "성남시 중원구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 성남시 중원구",
  },
  {
    code: "31023",
    name: "성남시 분당구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 성남시 분당구",
  },
  {
    code: "31030",
    name: "의정부시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 의정부시",
  },
  {
    code: "31041",
    name: "안양시 만안구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 안양시 만안구",
  },
  {
    code: "31042",
    name: "안양시 동안구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 안양시 동안구",
  },
  {
    code: "31051",
    name: "부천시 원미구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 부천시 원미구",
  },
  {
    code: "31052",
    name: "부천시 소사구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 부천시 소사구",
  },
  {
    code: "31053",
    name: "부천시 오정구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 부천시 오정구",
  },
  {
    code: "31060",
    name: "광명시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 광명시",
  },
  {
    code: "31070",
    name: "평택시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 평택시",
  },
  {
    code: "31080",
    name: "동두천시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 동두천시",
  },
  {
    code: "31091",
    name: "안산시 상록구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 안산시 상록구",
  },
  {
    code: "31092",
    name: "안산시 단원구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 안산시 단원구",
  },
  {
    code: "31101",
    name: "고양시 덕양구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 고양시 덕양구",
  },
  {
    code: "31103",
    name: "고양시 일산동구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 고양시 일산동구",
  },
  {
    code: "31104",
    name: "고양시 일산서구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 고양시 일산서구",
  },
  {
    code: "31110",
    name: "과천시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 과천시",
  },
  {
    code: "31120",
    name: "구리시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 구리시",
  },
  {
    code: "31130",
    name: "남양주시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 남양주시",
  },
  {
    code: "31140",
    name: "오산시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 오산시",
  },
  {
    code: "31150",
    name: "시흥시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 시흥시",
  },
  {
    code: "31160",
    name: "군포시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 군포시",
  },
  {
    code: "31170",
    name: "의왕시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 의왕시",
  },
  {
    code: "31180",
    name: "하남시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 하남시",
  },
  {
    code: "31191",
    name: "용인시 처인구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 용인시 처인구",
  },
  {
    code: "31192",
    name: "용인시 기흥구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 용인시 기흥구",
  },
  {
    code: "31193",
    name: "용인시 수지구",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 용인시 수지구",
  },
  {
    code: "31200",
    name: "파주시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 파주시",
  },
  {
    code: "31210",
    name: "이천시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 이천시",
  },
  {
    code: "31220",
    name: "안성시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 안성시",
  },
  {
    code: "31230",
    name: "김포시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 김포시",
  },
  {
    code: "31240",
    name: "화성시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 화성시",
  },
  {
    code: "31250",
    name: "광주시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 광주시",
  },
  {
    code: "31260",
    name: "양주시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 양주시",
  },
  {
    code: "31270",
    name: "포천시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 포천시",
  },
  {
    code: "31280",
    name: "여주시",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 여주시",
  },
  {
    code: "31550",
    name: "연천군",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 연천군",
  },
  {
    code: "31570",
    name: "가평군",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 가평군",
  },
  {
    code: "31580",
    name: "양평군",
    sidoCode: "31",
    sidoName: "울산광역시",
    fullName: "울산광역시 양평군",
  },
  {
    code: "32010",
    name: "춘천시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 춘천시",
  },
  {
    code: "32020",
    name: "원주시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 원주시",
  },
  {
    code: "32030",
    name: "강릉시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 강릉시",
  },
  {
    code: "32040",
    name: "동해시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 동해시",
  },
  {
    code: "32050",
    name: "태백시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 태백시",
  },
  {
    code: "32060",
    name: "속초시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 속초시",
  },
  {
    code: "32070",
    name: "삼척시",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 삼척시",
  },
  {
    code: "32510",
    name: "홍천군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 홍천군",
  },
  {
    code: "32520",
    name: "횡성군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 횡성군",
  },
  {
    code: "32530",
    name: "영월군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 영월군",
  },
  {
    code: "32540",
    name: "평창군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 평창군",
  },
  {
    code: "32550",
    name: "정선군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 정선군",
  },
  {
    code: "32560",
    name: "철원군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 철원군",
  },
  {
    code: "32570",
    name: "화천군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 화천군",
  },
  {
    code: "32580",
    name: "양구군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 양구군",
  },
  {
    code: "32590",
    name: "인제군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 인제군",
  },
  {
    code: "32600",
    name: "고성군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 고성군",
  },
  {
    code: "32610",
    name: "양양군",
    sidoCode: "32",
    sidoName: "기타",
    fullName: "기타 양양군",
  },
  {
    code: "33020",
    name: "충주시",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 충주시",
  },
  {
    code: "33030",
    name: "제천시",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 제천시",
  },
  {
    code: "33041",
    name: "청주시 상당구",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 청주시 상당구",
  },
  {
    code: "33042",
    name: "청주시 서원구",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 청주시 서원구",
  },
  {
    code: "33043",
    name: "청주시 흥덕구",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 청주시 흥덕구",
  },
  {
    code: "33044",
    name: "청주시 청원구",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 청주시 청원구",
  },
  {
    code: "33520",
    name: "보은군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 보은군",
  },
  {
    code: "33530",
    name: "옥천군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 옥천군",
  },
  {
    code: "33540",
    name: "영동군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 영동군",
  },
  {
    code: "33550",
    name: "진천군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 진천군",
  },
  {
    code: "33560",
    name: "괴산군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 괴산군",
  },
  {
    code: "33570",
    name: "음성군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 음성군",
  },
  {
    code: "33580",
    name: "단양군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 단양군",
  },
  {
    code: "33590",
    name: "증평군",
    sidoCode: "33",
    sidoName: "기타",
    fullName: "기타 증평군",
  },
  {
    code: "34011",
    name: "천안시 동남구",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 천안시 동남구",
  },
  {
    code: "34012",
    name: "천안시 서북구",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 천안시 서북구",
  },
  {
    code: "34020",
    name: "공주시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 공주시",
  },
  {
    code: "34030",
    name: "보령시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 보령시",
  },
  {
    code: "34040",
    name: "아산시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 아산시",
  },
  {
    code: "34050",
    name: "서산시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 서산시",
  },
  {
    code: "34060",
    name: "논산시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 논산시",
  },
  {
    code: "34070",
    name: "계룡시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 계룡시",
  },
  {
    code: "34080",
    name: "당진시",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 당진시",
  },
  {
    code: "34510",
    name: "금산군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 금산군",
  },
  {
    code: "34530",
    name: "부여군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 부여군",
  },
  {
    code: "34540",
    name: "서천군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 서천군",
  },
  {
    code: "34550",
    name: "청양군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 청양군",
  },
  {
    code: "34560",
    name: "홍성군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 홍성군",
  },
  {
    code: "34570",
    name: "예산군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 예산군",
  },
  {
    code: "34580",
    name: "태안군",
    sidoCode: "34",
    sidoName: "기타",
    fullName: "기타 태안군",
  },
  {
    code: "35011",
    name: "전주시 완산구",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 전주시 완산구",
  },
  {
    code: "35012",
    name: "전주시 덕진구",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 전주시 덕진구",
  },
  {
    code: "35020",
    name: "군산시",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 군산시",
  },
  {
    code: "35030",
    name: "익산시",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 익산시",
  },
  {
    code: "35040",
    name: "정읍시",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 정읍시",
  },
  {
    code: "35050",
    name: "남원시",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 남원시",
  },
  {
    code: "35060",
    name: "김제시",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 김제시",
  },
  {
    code: "35510",
    name: "완주군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 완주군",
  },
  {
    code: "35520",
    name: "진안군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 진안군",
  },
  {
    code: "35530",
    name: "무주군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 무주군",
  },
  {
    code: "35540",
    name: "장수군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 장수군",
  },
  {
    code: "35550",
    name: "임실군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 임실군",
  },
  {
    code: "35560",
    name: "순창군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 순창군",
  },
  {
    code: "35570",
    name: "고창군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 고창군",
  },
  {
    code: "35580",
    name: "부안군",
    sidoCode: "35",
    sidoName: "기타",
    fullName: "기타 부안군",
  },
  {
    code: "36010",
    name: "목포시",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 목포시",
  },
  {
    code: "36020",
    name: "여수시",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 여수시",
  },
  {
    code: "36030",
    name: "순천시",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 순천시",
  },
  {
    code: "36040",
    name: "나주시",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 나주시",
  },
  {
    code: "36060",
    name: "광양시",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 광양시",
  },
  {
    code: "36510",
    name: "담양군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 담양군",
  },
  {
    code: "36520",
    name: "곡성군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 곡성군",
  },
  {
    code: "36530",
    name: "구례군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 구례군",
  },
  {
    code: "36550",
    name: "고흥군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 고흥군",
  },
  {
    code: "36560",
    name: "보성군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 보성군",
  },
  {
    code: "36570",
    name: "화순군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 화순군",
  },
  {
    code: "36580",
    name: "장흥군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 장흥군",
  },
  {
    code: "36590",
    name: "강진군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 강진군",
  },
  {
    code: "36600",
    name: "해남군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 해남군",
  },
  {
    code: "36610",
    name: "영암군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 영암군",
  },
  {
    code: "36620",
    name: "무안군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 무안군",
  },
  {
    code: "36630",
    name: "함평군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 함평군",
  },
  {
    code: "36640",
    name: "영광군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 영광군",
  },
  {
    code: "36650",
    name: "장성군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 장성군",
  },
  {
    code: "36660",
    name: "완도군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 완도군",
  },
  {
    code: "36670",
    name: "진도군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 진도군",
  },
  {
    code: "36680",
    name: "신안군",
    sidoCode: "36",
    sidoName: "세종특별자치시",
    fullName: "세종특별자치시 신안군",
  },
  {
    code: "37011",
    name: "포항시 남구",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 포항시 남구",
  },
  {
    code: "37012",
    name: "포항시 북구",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 포항시 북구",
  },
  {
    code: "37020",
    name: "경주시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 경주시",
  },
  {
    code: "37030",
    name: "김천시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 김천시",
  },
  {
    code: "37040",
    name: "안동시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 안동시",
  },
  {
    code: "37050",
    name: "구미시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 구미시",
  },
  {
    code: "37060",
    name: "영주시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 영주시",
  },
  {
    code: "37070",
    name: "영천시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 영천시",
  },
  {
    code: "37080",
    name: "상주시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 상주시",
  },
  {
    code: "37090",
    name: "문경시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 문경시",
  },
  {
    code: "37100",
    name: "경산시",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 경산시",
  },
  {
    code: "37520",
    name: "의성군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 의성군",
  },
  {
    code: "37530",
    name: "청송군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 청송군",
  },
  {
    code: "37540",
    name: "영양군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 영양군",
  },
  {
    code: "37550",
    name: "영덕군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 영덕군",
  },
  {
    code: "37560",
    name: "청도군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 청도군",
  },
  {
    code: "37570",
    name: "고령군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 고령군",
  },
  {
    code: "37580",
    name: "성주군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 성주군",
  },
  {
    code: "37590",
    name: "칠곡군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 칠곡군",
  },
  {
    code: "37600",
    name: "예천군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 예천군",
  },
  {
    code: "37610",
    name: "봉화군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 봉화군",
  },
  {
    code: "37620",
    name: "울진군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 울진군",
  },
  {
    code: "37630",
    name: "울릉군",
    sidoCode: "37",
    sidoName: "기타",
    fullName: "기타 울릉군",
  },
  {
    code: "38030",
    name: "진주시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 진주시",
  },
  {
    code: "38050",
    name: "통영시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 통영시",
  },
  {
    code: "38060",
    name: "사천시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 사천시",
  },
  {
    code: "38070",
    name: "김해시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 김해시",
  },
  {
    code: "38080",
    name: "밀양시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 밀양시",
  },
  {
    code: "38090",
    name: "거제시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 거제시",
  },
  {
    code: "38100",
    name: "양산시",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 양산시",
  },
  {
    code: "38111",
    name: "창원시 의창구",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창원시 의창구",
  },
  {
    code: "38112",
    name: "창원시 성산구",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창원시 성산구",
  },
  {
    code: "38113",
    name: "창원시 마산합포구",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창원시 마산합포구",
  },
  {
    code: "38114",
    name: "창원시 마산회원구",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창원시 마산회원구",
  },
  {
    code: "38115",
    name: "창원시 진해구",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창원시 진해구",
  },
  {
    code: "38510",
    name: "의령군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 의령군",
  },
  {
    code: "38520",
    name: "함안군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 함안군",
  },
  {
    code: "38530",
    name: "창녕군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 창녕군",
  },
  {
    code: "38540",
    name: "고성군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 고성군",
  },
  {
    code: "38550",
    name: "남해군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 남해군",
  },
  {
    code: "38560",
    name: "하동군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 하동군",
  },
  {
    code: "38570",
    name: "산청군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 산청군",
  },
  {
    code: "38580",
    name: "함양군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 함양군",
  },
  {
    code: "38590",
    name: "거창군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 거창군",
  },
  {
    code: "38600",
    name: "합천군",
    sidoCode: "38",
    sidoName: "기타",
    fullName: "기타 합천군",
  },
  {
    code: "39010",
    name: "제주시",
    sidoCode: "39",
    sidoName: "기타",
    fullName: "기타 제주시",
  },
  {
    code: "39020",
    name: "서귀포시",
    sidoCode: "39",
    sidoName: "기타",
    fullName: "기타 서귀포시",
  },
];

export const REGION_MAP = new Map<string, RegionItem>(
  REGIONS.map((r) => [r.code, r]),
);

export const REGION_BY_NAME_MAP = new Map<string, RegionItem>(
  REGIONS.map((r) => [r.name, r]),
);
